CC=g++
CFLAGS=-std=gnu++11 -I

debug: main_coin_combinations_ii_down.cpp
	$(CC) main_coin_combinations_ii_down.cpp -o auto $(CFLAGS) && clear && ./auto && cat coin_combinations_ii_down.out 2>/dev/null
