CC=g++
CFLAGS=-std=gnu++11 -I

debug: main_247.cpp
	$(CC) main_247.cpp -o auto_247 $(CFLAGS) && clear && ./auto_247 && cat 247.out 2>/dev/null
CC=g++
CFLAGS=-std=gnu++11 -I

debug: main_247.cpp
	$(CC) main_247.cpp -o auto_247 $(CFLAGS) && clear && ./auto_247 && cat 247.out 2>/dev/null
