CC=g++
CFLAGS=-std=gnu++11 -I

debug: main_F-charmander-and-his-best-friends.cpp
	$(CC) main_F-charmander-and-his-best-friends.cpp -o auto $(CFLAGS) && clear && ./auto && cat F-charmander-and-his-best-friends.out 2>/dev/null
