CC=g++
CFLAGS=-std=gnu++11 -I

debug: main_1592.cpp
	$(CC) main_1592.cpp -o main1592 $(CFLAGS) && clear && ./main1592 && cat 1592.out 2>/dev/null
CC=g++
CFLAGS=-std=gnu++11 -I

debug: main_1592.cpp
	$(CC) main_1592.cpp -o main1592 $(CFLAGS) && clear && ./main1592 && cat 1592.out 2>/dev/null
