CC=g++
CFLAGS=-std=gnu++11

debug: main_increasing_subsequence_up_bins.cpp
	$(CC) main_increasing_subsequence_up_bins.cpp -o auto $(CFLAGS) && clear && ./auto && cat increasing_subsequence_up_bins.out 2>/dev/null
