CC=g++
CFLAGS=-std=gnu++11 -I

debug: main_1630down.cpp
	$(CC) main_1630down.cpp -o auto_1630down $(CFLAGS) && clear && ./auto_1630down && cat 1630down.out 2>/dev/null
CC=g++
CFLAGS=-std=gnu++11 -I

debug: main_1630down.cpp
	$(CC) main_1630down.cpp -o auto_1630down $(CFLAGS) && clear && ./auto_1630down && cat 1630down.out 2>/dev/null
